// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebApplication3.Models;

namespace WebApplication3.Migrations.Parrot
{
    [DbContext(typeof(ParrotContext))]
    [Migration("20170930233651_initial-7")]
    partial class initial7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication3.Models.Parrot", b =>
                {
                    b.Property<int>("ParrotId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Breeder");

                    b.Property<decimal>("Cost");

                    b.Property<bool>("Deceased");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<bool>("NewWorld");

                    b.Property<bool>("OldWorld");

                    b.Property<bool>("Sold");

                    b.Property<string>("Species");

                    b.HasKey("ParrotId");

                    b.ToTable("Parrot");
                });
#pragma warning restore 612, 618
        }
    }
}
