// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebApplication3.Models;

namespace WebApplication3.Migrations.Canary
{
    [DbContext(typeof(CanaryContext))]
    [Migration("20170930233833_initial-9")]
    partial class initial9
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication3.Models.Canary", b =>
                {
                    b.Property<int>("CanaryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Breeder");

                    b.Property<decimal>("Cost");

                    b.Property<bool>("Deceased");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<bool>("Sold");

                    b.Property<string>("Species");

                    b.HasKey("CanaryId");

                    b.ToTable("Canary");
                });
#pragma warning restore 612, 618
        }
    }
}
